TMPDIR .= "-${BB_CURRENT_MC}"

DISTRO = "xilinx-standalone-nolto"
DEFAULTTUNE = "cortexa53"
CONFIG_DTFILE = "${CONFIG_DTFILE_DIR}/k26-smk-kv-sdt-multidomain-cortexa53-0-baremetal.dts"
ESW_MACHINE = "psu_cortexa53_0"
