#@TYPE: Machine
#@NAME: Generic Kria Starter Kit
#@DESCRIPTION: Kria K24 SMK Starter Kit SOM

require include/k24-smk.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2024.2"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2024.2/hdf-examples/2024.2/2024.2_1023_1_10240131/external/k24-smk/k24-smk-2024.2_1023_1.xsa'
HDF_URI[sha256sum] = '457b200aeee1c55e44f35b617b4aae8cc8c573738680c3004ae00e985b7086c3'

#FPGA manager Variables
MACHINE_FEATURES += "fpga-overlay"
