#@TYPE: Machine
#@NAME: Generic Kria Starter Kit
#@DESCRIPTION: Kria K24 SMK Starter Kit SOM

require include/k24-smk.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.1"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.1/hdf-examples/2025.1/2025.1_0108_1_01090117/external/k24-smk/k24-smk-2025.1_0101_1.xsa'
HDF_URI[sha256sum] = 'd73ab0bd1a2a8dc4bddda1ba83a6aecdb8e7db6c47a18efb05251ecd008edb6b'

#FPGA manager Variables
MACHINE_FEATURES += "fpga-overlay"
