#@TYPE: Machine
#@NAME: Generic Kria Starter Kit
#@DESCRIPTION: Kria K24 SMK Starter Kit SOM

require include/k24-smk.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.1"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.1/hdf-examples/2025.1/2025.1_0217_1_02180117/external/k24-smk/k24-smk-2025.1_0217_1.xsa'
HDF_URI[sha256sum] = '419328482ebe79f41c4026ca3ea8f9e2f1d75bf84792e94af1d51c58ffe61c09'

#FPGA manager Variables
MACHINE_FEATURES += "fpga-overlay"
