#@TYPE: Machine
#@NAME: Generic k24c-sm
#@DESCRIPTION: Kria K24c SM Production SOM

require include/k24-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.1"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.1/hdf-examples/2025.1/2025.1_0319_1_03200117/external/k24c-sm/k24c-sm-2025.1_0319_1.xsa'
HDF_URI[sha256sum] = 'c3796d806e6deb773843e7d7627fb02a13ff4dca971b25d64d4607344ec80b7f'
