#@TYPE: Machine
#@NAME: Generic k24c-sm
#@DESCRIPTION: Kria K24c SM Production SOM

require include/k24-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.1"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.1/hdf-examples/2025.1/2025.1_0303_1_03040117/external/k24c-sm/k24c-sm-2025.1_0303_1.xsa'
HDF_URI[sha256sum] = 'fccc7a2e313357b4034b6f538a9636123e689bf07d22d654b4c7be30b75e2d22'
