#@TYPE: Machine
#@NAME: Generic k24c-sm
#@DESCRIPTION: Kria K24c SM Production SOM

require include/k24-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.2"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.2/hdf-examples/2025.2/2025.2_0811_1_08120113/external/k24c-sm/k24c-sm-2025.2_0811_1.xsa'
HDF_URI[sha256sum] = 'f465020ab0be86acb86552204637640389c98aa9451809e338cccc77335c3583'
