#@TYPE: Machine
#@NAME: Generic k24i-sm
#@DESCRIPTION: Kria K24i SM Production SOM

require include/k24-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2024.2"
XILINX_WITH_ESW = "xsct"

HDF_MACHINE = "k24i-sm"
