#@TYPE: Machine
#@NAME: Generic k24i-sm
#@DESCRIPTION: Kria K24i SM Production SOM

require include/k24-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.2"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.2/hdf-examples/2025.2/2025.2_0827_1_08280113/external/k24i-sm/k24i-sm-2025.2_0827_1.xsa'
HDF_URI[sha256sum] = '8d0d6d799aa8c8d6e82b812e1fdbbde9194d5df190ec2ab2cd9a9596aef705c9'
