#@TYPE: Machine
#@NAME: Generic k24i-sm
#@DESCRIPTION: Kria K24i SM Production SOM

require include/k24-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.2"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.2/hdf-examples/2025.2/2025.2_0623_1_06240113/external/k24i-sm/k24i-sm-2025.2_0623_1.xsa'
HDF_URI[sha256sum] = '65d398bd58b4f55619fe3b0a68aa61b4ff0349cb1c49b679a607a6e501bc061d'
