#@TYPE: Machine
#@NAME: Generic Kria Starter Kit
#@DESCRIPTION: Kria K26 SOM + Starter kit

require include/k26-smk.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.1"
XILINX_WITH_ESW = "xsct"

# Set Image Recovery Depends for XSCT machine
IMGRCRY_DEPENDS = "${@'image-recovery-make:do_deploy' if d.getVar('XILINX_WITH_ESW') == 'xsct' else ''}"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.1/hdf-examples/2025.1/2025.1_0505_1_05060117/external/k26-smk/k26-smk-2025.1_0505_1.xsa'
HDF_URI[sha256sum] = 'b6dfcbd576d0cb82b62b088adfd753f372458c7fab735807b146a02e6c35105c'

# NOTE: For K26 starterkit QEMU to boot it needs to have a carrier card configured. The default
# card is set to KV260, but this can be changed by commenting out the lines below and uncomminting
# the KR260 settings.

# K26 + KV260
require include/kria-qemu-kv.inc

# K26 + KR260
#require include/kria-qemu-kr.inc
#

#FPGA manager Variables
MACHINE_FEATURES += "fpga-overlay"
