#@TYPE: Machine
#@NAME: Generic Kria Starter Kit
#@DESCRIPTION: Kria K26 SOM + Starter kit

require include/k26-smk.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2024.2"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2024.2/hdf-examples/2024.2/2024.2_1023_1_10240131/external/k26-smk/k26-smk-2024.2_1023_1.xsa'
HDF_URI[sha256sum] = 'ff81bd4772744635393b6e9395da96b9609419f3b69918202f3de3cc83f9d127'

# NOTE: For K26 starterkit QEMU to boot it needs to have a carrier card configured. The default
# card is set to KV260, but this can be changed by commenting out the lines below and uncomminting
# the KR260 settings.

# K26 + KV260
require include/kria-qemu-kv.inc

# K26 + KR260
#require include/kria-qemu-kr.inc
#

#FPGA manager Variables
MACHINE_FEATURES += "fpga-overlay"
