#@TYPE: Machine
#@NAME: Generic k26-sm
#@DESCRIPTION: Kria K26 SM Production SOM

require include/k26-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.1"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.1/hdf-examples/2025.1/2025.1_0428_1_04290117/external/k26-sm/k26-sm-2025.1_0428_1.xsa'
HDF_URI[sha256sum] = 'e7fa4942ee5660ac45ce60fb7efc55c9587a36f4c912985309fead6ae248e09f'
