#@TYPE: Machine
#@NAME: Generic k26-sm
#@DESCRIPTION: Kria K26 SM Production SOM

require include/k26-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2025.2"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2025.2/hdf-examples/2025.2/2025.2_0827_1_08280113/external/k26-sm/k26-sm-2025.2_0827_1.xsa'
HDF_URI[sha256sum] = '0686eb481f299498f94baec3d8a37ae4a914f393288ce871d6cd5b55472a6555'
