#@TYPE: Machine
#@NAME: Generic k26-sm
#@DESCRIPTION: Kria K26 SM Production SOM

require include/k26-sm.inc

# This is an 'XSCT' based BSP
XILINX_XSCT_VERSION = "2024.2"
XILINX_WITH_ESW = "xsct"

# Add system XSA
HDF_URI = 'https://petalinux.xilinx.com/sswreleases/rel-v2024/hdf-examples/2024.2/2024.2_0911_1_09120231/external/k26-sm/k26-sm-2024.2_0911_1.xsa'
HDF_URI[sha256sum] = '4f61e4c8a2663433e0a88e1121779418acc2eab9175cf272882fc2eee67e0ea3'
