YAML_SERIAL_CONSOLE_STDIN:k26 ?= "psu_uart_1"
YAML_SERIAL_CONSOLE_STDOUT:k26 ?= "psu_uart_1"

YAML_COMPILER_FLAGS:append:k26 = " -DBOARD_SHUTDOWN_PIN=2 -DBOARD_SHUTDOWN_PIN_STATE=0 -DENABLE_EM -DENABLE_MOD_OVERTEMP -DOVERTEMP_DEGC=90.0 -DENABLE_DYNAMIC_MIO_CONFIG -DENABLE_IOCTL -DCONNECT_PMU_GPO_2_VAL=0"
